<?php

namespace App\Filament\App\Resources\UserResource\Pages;

use App\Filament\App\Resources\UserResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;
use App\Models\User;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\Auth;

class ListUsers extends ListRecords
{
    protected static string $resource = UserResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }
    protected function getTableQuery(): ?Builder
    {
        if (Auth::user()?->hasRole('admin')) {
            $query = User::query();
            $user = Auth::user();

            $query->where(function ($subquery) use ($user) {
                $subquery->where('id', $user->id);
                $subquery->orWhere('created_by', $user->id);
            });
            return $query;
        } else {
            return parent::getTableQuery()->where('id', auth()->id()); // TODO: Change the autogenerated stub
        }
    }
}
