<?php

namespace App\Filament\App\Resources\PostResource\Pages;

use App\Filament\App\Resources\PostResource;
use App\Models\Post;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;

class ListPosts extends ListRecords
{
    protected static string $resource = PostResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }
   protected function getTableQuery(): ?Builder
   {
       if (Auth::user()?->hasRole('admin')){
           return parent::getTableQuery()->where('shop_id',auth()->id()); // TODO: Change the autogenerated stub
       }
       return parent::getTableQuery(); // TODO: Change the autogenerated stub
   }
}
